id = "panda-plus-theme"
name = "Panda+ Theme"
version = "0.1.0"
schema_version = 1
authors = ["Luciano Ratamero <luciano@ratamero.com>"]
description = "Panda themes with extra contrast for Zed"
repository = "https://github.com/lucianoratamero/panda-plus-theme-zed"
